In [1]:
import pandas as pd

In [13]:
draft1=pd.read_csv('ex1.csv')

In [14]:
draft1

   0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [15]:
draft1.head(2)

   0  1  2  3        4
0  a  b  c  d  message
1  1  2  3  4    hello

In [28]:
draft2=pd.read_table('test.tsv')

In [29]:
draft2

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar
sumit  sumit  sumit  sumit  sumit  sumit

In [30]:
draft3=pd.read_csv('ex1.csv')

In [31]:
draft3

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [32]:
draft4=pd.read_table('ex1.csv',sep=',')

In [33]:
draft4

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [34]:
draft5= pd.read_csv('test.tsv',sep='\t')

In [35]:
draft5

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar
sumit  sumit  sumit  sumit  sumit  sumit

In [41]:
draft5= pd.read_csv('ex1.csv',header=None)
draft5

   0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [49]:
draft6= pd.read_csv('ex2.csv',names=['1stCol','2ndCol','3rdCol','4thCol','5thCol'])
draft6
type(draft6)

pandas.core.frame.DataFrame

In [51]:
draft7=pd.read_csv('csv_mindex.csv')
draft7

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [52]:
draft8=pd.read_csv('csv_mindex.csv',index_col=['key1'])
draft8

     key2  value1  value2
key1
one     a       1       2
one     b       3       4
one     c       5       6
one     d       7       8
two     a       9      10
two     b      11      12
two     c      13      14
two     d      15      16

In [54]:
draft9=pd.read_csv('csv_mindex.csv',index_col=['key1','key2'])
draft9

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [56]:
draft10=pd.read_csv('ex4.csv')
draft10

                                                                      # hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... NaN      NaN NaN      NaN
# who reads CSV files with computers                anyway? NaN NaN      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo

In [60]:
draft11=pd.read_csv('ex4.csv',skiprows=[0,2,3],header=None)
draft11

   0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [67]:
draft12=pd.read_csv('ex5.csv')
draft12

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [68]:
pd.isnull(draft12)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [71]:
draft13=pd.read_csv('ex5.csv',na_values=['NULL',2,'three'])
draft13

  something  a     b     c   d message
0       one  1   NaN   3.0   4     NaN
1       two  5   6.0   NaN   8   world
2       NaN  9  10.0  11.0  12     foo

In [76]:
url = "http://www.basketball-reference.com/leagues/NBA_2015_totals.html"

BB_data = pd.read_html(url)

BB_data[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [77]:
type(BB_data)

list

In [78]:
type(BB_data[0])

pandas.core.frame.DataFrame

In [92]:
BB_data[0].dtypes

Rk        object
Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG%       object
3P        object
3PA       object
3P%       object
2P        object
2PA       object
2P%       object
eFG%      object
FT        object
FTA       object
FT%       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
dtype: object

In [79]:
basketBall_Data=BB_data[0]

In [80]:
basketBall_Data

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [81]:
basketBall_Data['Player']

0          Quincy Acy
1        Jordan Adams
2        Steven Adams
3         Jeff Adrien
4       Arron Afflalo
            ...
670    Thaddeus Young
671    Thaddeus Young
672    Thaddeus Young
673       Cody Zeller
674      Tyler Zeller
Name: Player, Length: 675, dtype: object

In [82]:
type(basketBall_Data['Player'])

pandas.core.series.Series

In [88]:
basketBall_Data[['Player','Age','Pos']].head(10)

           Player Age Pos
0      Quincy Acy  24  PF
1    Jordan Adams  20  SG
2    Steven Adams  21   C
3     Jeff Adrien  28  PF
4   Arron Afflalo  29  SG
5   Arron Afflalo  29  SG
6   Arron Afflalo  29  SG
7   Alexis Ajinça  26   C
8  Furkan Aldemir  23  PF
9    Cole Aldrich  26   C

In [91]:
basketBall_Data.dtypes

Rk        object
Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG%       object
3P        object
3PA       object
3P%       object
2P        object
2PA       object
2P%       object
eFG%      object
FT        object
FTA       object
FT%       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
dtype: object

In [109]:
pd.options.display.max_rows = 10

In [110]:
basketBall_Data.dtypes

Rk        object
Player    object
Pos       object
Age       object
Tm        object
           ...
STL       object
BLK       object
TOV       object
PF        object
PTS       object
Length: 30, dtype: object

In [111]:
draft14=pd.read_csv('ex6.csv')
draft14

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [115]:
pd.read_csv('ex6.csv',nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [117]:
chunk=pd.read_csv('ex6.csv',chunksize=10)
chunk

In [120]:
draft15=pd.read_csv('ex5.csv')
draft15

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [122]:
draft15.to_csv('writeToex5.csv')

In [126]:
import sys
draft15.to_csv('writeToex5_1.csv',sep='#')

In [127]:
draft15.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [129]:
draft15.to_csv('writeToex5_1.csv',sep='#',index='false',header='false')

In [133]:
draft15.to_csv('writeToex5_2.csv',index='false',columns=['a', 'b', 'c'])

In [136]:
draft15.to_csv('writeToex5_3.csv',index='false',columns=['a', 'b', 'c','d'])

In [138]:
pd.date_range('1/1/2020',periods=7)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D')

In [140]:
pd.date_range('1/1/2020',periods=7,freq='M')

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31', '2020-06-30', '2020-07-31'],
              dtype='datetime64[ns]', freq='M')

In [142]:
pd.date_range('1/1/2020',periods=7,freq='Y')

DatetimeIndex(['2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31',
               '2024-12-31', '2025-12-31', '2026-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [143]:
import numpy as np

In [144]:
ts=pd.Series(np.arange(7))

In [148]:
ts

0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int32

In [150]:
ts1=pd.Series(np.arange(1,8))
ts1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [151]:
ts1[2]

3

In [161]:
dates=pd.date_range('1/1/2022',periods=7)
ts2=pd.Series(np.arange(1,8),index=dates)
ts2.to_csv('tseries.csv',header='False')
ts2

2022-01-01    1
2022-01-02    2
2022-01-03    3
2022-01-04    4
2022-01-05    5
2022-01-06    6
2022-01-07    7
Freq: D, dtype: int32

In [145]:
range(7.0)  # range function will never accept float

TypeError: 'float' object cannot be interpreted as an integer

In [155]:
dates=pd.date_range('1/1/2022',periods=7)
ts3=pd.Series(np.arange(1,8),index=['row1','row2','row3','row4','row5','row6','row7'])  #providing our own indexes
ts3

row1    1
row2    2
row3    3
row4    4
row5    5
row6    6
row7    7
dtype: int32

In [147]:
np.arange(1.0,7.0,.5) # arange function accepts float values

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [157]:
ts3['row5']

5

In [166]:
import csv
f=open('ex7.csv')

reader=csv.reader(f)
reader

In [164]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [167]:
for line in f:
    print(line)

"a","b","c"

"1","2","3"

"1","2","3"

In [168]:
with open('ex7.csv') as f:
    lines=list(csv.reader(f))

In [169]:
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [170]:
header,values=lines[0],lines[1:]

In [171]:
header

['a', 'b', 'c']

In [172]:
values

[['1', '2', '3'], ['1', '2', '3']]

In [173]:
type(header)

list

In [174]:
type(values)

list

In [ ]:
# zip always returns a tuple. It tries to make pairs

In [175]:
for i in zip([1,2,3],[4,5,6]):
    print(i)

(1, 4)
(2, 5)
(3, 6)

In [177]:
for i in zip([1,2,3],[4,5,6],[7,8,9]):
    print(i)

(1, 4, 7)
(2, 5, 8)
(3, 6, 9)

In [182]:
for i in zip(*values):    # * here is used to make sure zip function treats the values as a nested list .otherwise it will treat it as a single list
        print(i)

('1', '1')
('2', '2')
('3', '3')

In [183]:
for i in zip(values):
        print(i)

(['1', '2', '3'],)
(['1', '2', '3'],)

In [184]:
z= zip(header,zip(*values))

In [185]:
z

In [186]:
for i in z:
    print(i)

('a', ('1', '1'))
('b', ('2', '2'))
('c', ('3', '3'))

In [187]:
type(z)

zip

In [189]:
data_dict={h:v for h,v in zip(header,zip(*values))}  # using dictionary comprehension

In [190]:
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [191]:
# Normal way without Dictionary Comprehension

d={}
for i in zip(header,zip(*values)):
    d[i[0]]=i[1]
    
d

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [192]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [193]:
type(obj) # """-multiple line string

str

In [195]:
import json
result=json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [196]:
type(result)

dict

In [197]:
asjson=json.dumps(result)
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [198]:
type(asjson)

str

In [200]:
result['siblings']

[{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
 {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]

In [203]:
pd.DataFrame(result['siblings'])

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [204]:
pd.DataFrame(result['siblings'],columns=['name','age','pets'])

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [205]:
pd.DataFrame(result['siblings'],columns=['sumit','name','age','pets'])

   sumit   name  age                    pets
0    NaN  Scott   30            [Zeus, Zuko]
1    NaN  Katie   38  [Sixes, Stache, Cisco]

In [206]:
data=pd.read_json('example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [207]:
print(data.to_json())

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [208]:
print(data.to_json(orient='records'))

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

In [210]:
type(data.to_json())

str

In [214]:
tables=pd.read_html('fdic_failed_bank_list.html')
len(tables)

1

In [215]:
failures=tables[0]

In [216]:
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [217]:
failures.dtypes

Bank Name                object
City                     object
ST                       object
CERT                      int64
Acquiring Institution    object
Closing Date             object
Updated Date             object
dtype: object

In [219]:
failures['Closing Date']

0      September 23, 2016
1         August 19, 2016
2             May 6, 2016
3          April 29, 2016
4          March 11, 2016
              ...
542         July 27, 2001
543           May 3, 2001
544      February 2, 2001
545     December 14, 2000
546      October 13, 2000
Name: Closing Date, Length: 547, dtype: object

In [223]:
type(failures['Closing Date'])

pandas.core.series.Series

In [235]:
close_timestamps=pd.to_datetime(failures['Closing Date'])

In [236]:
close_timestamps

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[ns]

In [233]:
type(close_timestamps)

pandas.core.series.Series

In [224]:
type(close_timestamps[0])

pandas._libs.tslibs.timestamps.Timestamp

In [237]:
close_timestamps.dt.year

0      2016
1      2016
2      2016
3      2016
4      2016
       ...
542    2001
543    2001
544    2001
545    2000
546    2000
Name: Closing Date, Length: 547, dtype: int64

In [244]:
close_timestamps.dt.day_name

In [248]:
close_timestamps.dt.year.value_counts()

2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, Length: 15, dtype: int64

In [254]:
close_timestamps.dt.year.groupby(close_timestamps.dt.year).count()

Closing Date
2000     2
2001     4
2002    11
2003     3
2004     4
        ..
2012    51
2013    24
2014    18
2015     8
2016     5
Name: Closing Date, Length: 15, dtype: int64

In [262]:
# BINARY DATA FORMATS

In [257]:
frame=pd.read_csv('ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [258]:
frame.to_pickle('frame_pickle')

In [259]:
pd.read_pickle('frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [260]:
pd.read_csv('frame_pickle')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

In [261]:
#WEB APIS

In [265]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [268]:
data= resp.json()
type(data)
data[2]['html_url']

'https://github.com/pandas-dev/pandas/issues/48905'

In [270]:
type(data)

list

In [271]:
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48907',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48907/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48907/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48907/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/48907',
  'id': 1393408412,
  'node_id': 'PR_kwDOAA0YD84__TDs',
  'number': 48907,
  'title': 'TYP: Axis-related annotations',
  'user': {'login': 'twoertwein',
   'id': 6618166,
   'node_id': 'MDQ6VXNlcjY2MTgxNjY=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6618166?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/twoertwein',
   'html_url': 'https://github.com/twoertwein',
   'followers_url': 'https://api.github.com/users/twoertwein/followers',
   'following_url': 'https://api.github.com/users/twoertwein/following{/other_user}',
   'gists_url': 'https://api.github.com/users/twoertwein/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/twoertwein/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/twoertwein/subscriptions',
   'organizations_url': 'https://api.github.com/users/twoertwein/orgs',
   'repos_url': 'https://api.github.com/users/twoertwein/repos',
   'events_url': 'https://api.github.com/users/twoertwein/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/twoertwein/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-10-01T13:41:30Z',
  'updated_at': '2022-10-01T13:42:52Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/48907',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/48907',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/48907.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/48907.patch',
   'merged_at': None},
  'body': 'I tried to limit `_typing.AxisInt` to `Literal[0, 1]`. That might be feasible in the future when mypy supports more literal math (e.g., `1 - Literal[0, 1] = Literal[0, 1]`), but would cause too many errors for now.\r\n\r\nThis PR adds a few Axis-related annotations but does not restrict `AxisInt` to `{0, 1}`.',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48907/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48907/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48906',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48906/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48906/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48906/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/48906',
  'id': 1393402202,
  'node_id': 'PR_kwDOAA0YD84__R35',
  'number': 48906,
  'title': 'Fix: Reanme duplicate function names in unittests',
  'user': {'login': 'FloHofstetter',
   'id': 13952785,
   'node_id': 'MDQ6VXNlcjEzOTUyNzg1',
   'avatar_url': 'https://avatars.githubusercontent.com/u/13952785?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/FloHofstetter',
   'html_url': 'https://github.com/FloHofstetter',
   'followers_url': 'https://api.github.com/users/FloHofstetter/followers',
   'following_url': 'https://api.github.com/users/FloHofstetter/following{/other_user}',
   'gists_url': 'https://api.github.com/users/FloHofstetter/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/FloHofstetter/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/FloHofstetter/subscriptions',
   'organizations_url': 'https://api.github.com/users/FloHofstetter/orgs',
   'repos_url': 'https://api.github.com/users/FloHofstetter/repos',
   'events_url': 'https://api.github.com/users/FloHofstetter/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/FloHofstetter/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-10-01T13:18:22Z',
  'updated_at': '2022-10-01T13:44:53Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/48906',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/48906',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/48906.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/48906.patch',
   'merged_at': None},
  'body': '- [ ] xref https://github.com/pandas-dev/pandas/issues/48855 - one of many style checks, still needs work.\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48906/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48906/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48905',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48905/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48905/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48905/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/48905',
  'id': 1393393576,
  'node_id': 'I_kwDOAA0YD85TDX-o',
  'number': 48905,
  'title': 'BUG: regression in MultiIndex.isin when index contains NA',
  'user': {'login': 'lukemanley',
   'id': 8519523,
   'node_id': 'MDQ6VXNlcjg1MTk1MjM=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8519523?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lukemanley',
   'html_url': 'https://github.com/lukemanley',
   'followers_url': 'https://api.github.com/users/lukemanley/followers',
   'following_url': 'https://api.github.com/users/lukemanley/following{/other_user}',
   'gists_url': 'https://api.github.com/users/lukemanley/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/lukemanley/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/lukemanley/subscriptions',
   'organizations_url': 'https://api.github.com/users/lukemanley/orgs',
   'repos_url': 'https://api.github.com/users/lukemanley/repos',
   'events_url': 'https://api.github.com/users/lukemanley/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/lukemanley/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 32815646,
    'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression',
    'name': 'Regression',
    'color': 'e11d21',
    'default': False,
    'description': 'Functionality that used to work in a prior pandas version'},
   {'id': 71268330,
    'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex',
    'name': 'MultiIndex',
    'color': '207de5',
    'default': False,
    'description': None}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-10-01T13:01:27Z',
  'updated_at': '2022-10-01T13:05:27Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': '### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\n\r\nmi1 = pd.MultiIndex.from_tuples([(1, pd.NA)])\r\nmi2 = pd.MultiIndex.from_tuples([(1, 1), (1, 2)])\r\n\r\nmi2.isin(mi1)\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\noutput:\r\n```\r\narray([True, True])    # <- main\r\narray([False, False])  # <- 1.5.0\r\n```\r\n\r\nRegression is on main only and looks to be a result of #48622. \r\n\r\nThe bug is not in `MultiIndex.isin` per se, but #48622 looks to have exposed the underlying bug to `MultiIndex.isin`.\r\n\r\nOpen PR #48877 will fix the underlying bug. \r\n\r\n### Expected Behavior\r\n\r\n```\r\narray([False, False])\r\n```\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nReplace this line with the output of pd.show_versions()\r\n\r\n</details>\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48905/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48905/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48902',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48902/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48902/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48902/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/48902',
  'id': 1393277711,
  'node_id': 'PR_kwDOAA0YD84_-4wD',
  'number': 48902,
  'title': 'DOC: Added mean function as method of Resampler and updated docstring',
  'user': {'login': 'donghyyun',
   'id': 31753237,
   'node_id': 'MDQ6VXNlcjMxNzUzMjM3',
   'avatar_url': 'https://avatars.githubusercontent.com/u/31753237?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/donghyyun',
   'html_url': 'https://github.com/donghyyun',
   'followers_url': 'https://api.github.com/users/donghyyun/followers',
   'following_url': 'https://api.github.com/users/donghyyun/following{/other_user}',
   'gists_url': 'https://api.github.com/users/donghyyun/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/donghyyun/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/donghyyun/subscriptions',
   'organizations_url': 'https://api.github.com/users/donghyyun/orgs',
   'repos_url': 'https://api.github.com/users/donghyyun/repos',
   'events_url': 'https://api.github.com/users/donghyyun/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/donghyyun/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-10-01T07:05:25Z',
  'updated_at': '2022-10-01T07:46:42Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/48902',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/48902',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/48902.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/48902.patch',
   'merged_at': None},
  'body': '- [x] closes #48803 \r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48902/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48902/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48901',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48901/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48901/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48901/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/48901',
  'id': 1393193640,
  'node_id': 'PR_kwDOAA0YD84_-nB2',
  'number': 48901,
  'title': 'BUG: DataFrame from dict with non-nano Timedelta',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-10-01T02:35:38Z',
  'updated_at': '2022-10-01T02:35:38Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/48901',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/48901',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/48901.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/48901.patch',
   'merged_at': None},
  'body': '- [ ] closes #xxxx\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n\r\nxref #44504\r\n\r\nThis is motivated by a branch (upcoming PR) that makes the Timedelta constructor preserve resolution when passed a np.timedelta64 object.  Without this change, test_constructor_dict_timedelta64_index fails because of a dict lookup in lib.fast_multiget.\r\n\r\nFor non-nano Timedeltas this does significantly hurt performance:\r\n\r\n```\r\nIn [1]: import pandas as pd\r\nIn [2]: td = pd.Timedelta(days=1, minutes=3)\r\nIn [3]: td2 = td._as_unit("ms")\r\n\r\nIn [4]: %timeit hash(td)\r\n145 ns ± 15.5 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)  # <- main\r\n131 ns ± 3.43 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)  # <- PR\r\n\r\nIn [5]: %timeit hash(td2)\r\n138 ns ± 16.8 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)  # <- main\r\n1.8 µs ± 42.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)  # <- PR\r\n```\r\n\r\nI expect there\'s room for optimization.  Something like:\r\n\r\n\r\n```\r\nif self._is_in_pytimedelta_bounds() and not self._has_ns():\r\n    return timedelta.__hash__(self)\r\nelse:\r\n    return self._hash_version_in this_pr()\r\n```',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48901/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48901/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48900',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48900/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48900/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48900/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/48900',
  'id': 1393169792,
  'node_id': 'PR_kwDOAA0YD84_-h_l',
  'number': 48900,
  'title': 'PERF: algos.union_with_duplicates',
  'user': {'login': 'lukemanley',
   'id': 8519523,
   'node_id': 'MDQ6VXNlcjg1MTk1MjM=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8519523?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lukemanley',
   'html_url': 'https://github.com/lukemanley',
   'followers_url': 'https://api.github.com/users/lukemanley/followers',
   'following_url': 'https://api.github.com/users/lukemanley/following{/other_user}',
   'gists_url': 'https://api.github.com/users/lukemanley/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/lukemanley/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/lukemanley/subscriptions',
   'organizations_url': 'https://api.github.com/users/lukemanley/orgs',
   'repos_url': 'https://api.github.com/users/lukemanley/repos',
   'events_url': 'https://api.github.com/users/lukemanley/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/lukemanley/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 8935311,
    'node_id': 'MDU6TGFiZWw4OTM1MzEx',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance',
    'name': 'Performance',
    'color': 'a10c02',
    'default': False,
    'description': 'Memory or execution speed performance'},
   {'id': 71268330,
    'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex',
    'name': 'MultiIndex',
    'color': '207de5',
    'default': False,

In [272]:
issues=pd.DataFrame(data)
issues.head(3)

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48907,1393408412,PR_kwDOAA0YD84__TDs,48907,TYP: Axis-related annotations,...,None,CONTRIBUTOR,None,False,{'url': 'https://api.github.com/repos/pandas-d...,I tried to limit `_typing.AxisInt` to `Literal...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48906,1393402202,PR_kwDOAA0YD84__R35,48906,Fix: Reanme duplicate function names in unittests,...,None,NONE,None,False,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] xref https://github.com/pandas-dev/panda...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48905,1393393576,I_kwDOAA0YD85TDX-o,48905,BUG: regression in MultiIndex.isin when index ...,...,None,CONTRIBUTOR,None,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None

In [274]:
issues['assignees']

0    []
1    []
2    []
3    []
4    []
5    []
6    []
7    []
8    []
9    []
Name: assignees, dtype: object

In [275]:
issues2=pd.DataFrame(data,columns=['number','title','labels','state'])

In [276]:
issues2

,number,title,labels,state
0,48907,TYP: Axis-related annotations,[],open
1,48906,Fix: Reanme duplicate function names in unittests,[],open
2,48905,BUG: regression in MultiIndex.isin when index ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
3,48902,DOC: Added mean function as method of Resample...,[],open
4,48901,BUG: DataFrame from dict with non-nano Timedelta,[],open
...,...,...,...,...
25,48869,ENH: Use a proper CSS parser for pandas Styler...,[],open
26,48868,ENH: Use a proper CSS parser for pandas Styler...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
27,48867,BUG/API: setting behavior inserting negative n...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
28,48864,API: what should float(pd.NA) return?,"[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...",open
29,48862,REF: helpers to de-duplicate datetimelike arit...,"[{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open